[package]
name = "solana-pda-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "example_runner"
path = "example_runner.rs"

[dependencies]
tokio = { workspace = true }
solana-sdk = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }